---------- BÖLÜM 11: Alt Sorgu Örnekleri ----------
SELECT URUNAD, COUNT(*) AS 'ÜRÜN AD' FROM TBLHAREKET
INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID
GROUP BY URUNAD ORDER BY COUNT(*) ASC

SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE 
KATEGORI=1)

--ÖDEV: Yukarýdaki sorguyu bu seferde KATEGORI deðerine 1 yerine 'BÝLGÝSAYAR' diyerek getirmeye çalýþýn.
SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE 
KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR'))

SELECT * FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI 
WHERE MUSTERISEHIR='ADANA')

SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE 
KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))

SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI 
WHERE MUSTERISEHIR='ADANA' OR MUSTERISEHIR='ANKARA')

--ÖDEV: 'ADANA','ANKARA','BURSA' þehirlerimizdeki müþterilerimizin toplam yaptýðý alýþveriþin tutarýný bulunuz
SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI 
WHERE MUSTERISEHIR IN('ADANA','ANKARA','BURSA'))

SELECT * FROM TBLHAREKET WHERE URUN=1
--TBLURUNLER tablosunda stok azaltma yapalým
UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=1) WHERE URUNID=1

CREATE TABLE TBLKASA
(
TOPLAM DECIMAL(18,2)
)

INSERT INTO TBLKASA VALUES(0)

SELECT * FROM TBLKASA

UPDATE TBLKASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBLHAREKET)

---------- BÖLÜM 12: Tetikleyiciler / TRIGGER OLUÞTURMA ----------
CREATE TABLE TBLSAYAC
(
ISLEM INT
)

INSERT INTO TBLSAYAC VALUES(0)

UPDATE TBLSAYAC SET ISLEM=(SELECT COUNT(*) FROM TBLHAREKET)

--TBLHAREKET tablosuna yeni bir veri giriþi yaptýðýmýz zaman sayaç deðeri yani TBLSAYAC tablosundaki ISLEM deðeri 1 artsýn
CREATE TRIGGER ISLEMARTIS
ON TBLHAREKET
AFTER INSERT
AS
UPDATE TBLSAYAC SET ISLEM=ISLEM+1

/*
NOT: ISLEMARTIS adýndaki trigger, TBLHAREKET tablosunun altýna gelmiþ oldu. Kontrol edebilirsiniz.

TRIGGER sayesinde TBLHAREKET tablosundaki kayýt sayýsý (yani iþlem sayýsý) arttýðý zaman otomatik
olarak bunu algýlayýp TBLSAYAC tablosunda bu deðiþikliði yapýyor.
*/

CREATE TABLE TBLTOPLAMKATEGORI
(
ADET TINYINT
)

UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBLKATEGORI)

CREATE TRIGGER KATEGORIARTIS
ON TBLKATEGORI
AFTER INSERT
AS
UPDATE TBLTOPLAMKATEGORI SET ADET+=1

CREATE TRIGGER KATEGORIAZALIS
ON TBLKATEGORI
AFTER DELETE
AS
UPDATE TBLTOPLAMKATEGORI SET ADET-=1
