---------- BÖLÜM 5: Birleþtirme Ýþlemleri ----------
--INNER JOIN (KESÝÞÝM): Karþýlaþtýrýlan iki tablo arasýnda yalnýzca bu iki tablonun kesiþimlerinde bulunan alanlarý verir.  
SELECT * FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER
ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--LEFT JOIN: Karþýlaþtýrýlan iki tablo arasýnda yalnýzca 1.tabloda bulunan alanlarý (kesiþim kümesi dahil) verir. 
SELECT * FROM TBLNOTLAR
LEFT JOIN TBLOGRENCILER
ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--RIGHT JOIN: Karþýlaþtýrýlan iki tablo arasýnda yalnýzca 2.tabloda bulunan alanlarý (kesiþim kümesi dahil) verir. 
SELECT * FROM TBLNOTLAR
RIGHT JOIN TBLOGRENCILER
ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--FULL JOIN (BÝRLEÞÝM): Karþýlaþtýrýlan iki tabloda bulunan bütün alanlarý (kesiþim kümesi dahil) verir. 
SELECT * FROM TBLNOTLAR
FULL JOIN TBLOGRENCILER
ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--UNION: Ýki farklý tabloya ait bütün verileri birinci tablonun sütun adlarýna göre birleþtirir.
SELECT * FROM TBLKULUPLER UNION SELECT * FROM TBLDERSLER

---------- BÖLÜM 6: Aritmetik Fonksiyonlar ----------
UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1
SELECT * FROM TBLNOTLAR WHERE DERS=1
UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100

UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1

SELECT AVG(ORTALAMA) FROM TBLNOTLAR WHERE DERS=1

/* ÖDEV: Sýnýf ortalamasýnýn altýnda olan öðrencilerin "Durum2" sütunlarýnýn yanýna "Altýnda", 
aksi durumda üstünde yazdýran sorguyu hazýrlayýn.*/
--1.YOL
SELECT *,
    CASE 
        WHEN ORTALAMA < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) THEN 'Altýnda'
        ELSE 'Üstünde'
    END AS Durum2
FROM TBLNOTLAR;

--2.YOL
SELECT n.*, 'Altýnda' AS Durum2
FROM TBLNOTLAR n
INNER JOIN (SELECT AVG(ORTALAMA) AS ORTALAMA FROM TBLNOTLAR) avg
ON n.ORTALAMA < avg.ORTALAMA
UNION
SELECT n.*, 'Üstünde' AS Durum2
FROM TBLNOTLAR n
INNER JOIN (SELECT AVG(ORTALAMA) AS ORTALAMA FROM TBLNOTLAR) avg
ON n.ORTALAMA >= avg.ORTALAMA;

--3.YOL
Select *, 'Üstünde' as 'DURUM2' From TBLNOTLAR Where ORTALAMA>(Select Avg(ORTALAMA) From TBLNOTLAR Where Ders IN (1,2))
Union
Select *, 'Altýnda' as 'DURUM2' From TBLNOTLAR Where ORTALAMA<(Select Avg(ORTALAMA) From TBLNOTLAR Where Ders IN (1,2))

--ABS: MUTLAK DEÐER
SELECT ABS(-85) AS 'MUTLAK DEÐER'

--POWER: ÜS ALMA
SELECT POWER(2,4) AS 'ÜS ALMA'

SELECT POWER(SINAV1,2) FROM TBLNOTLAR

--SQRT: KAREKÖK ALMA
SELECT SQRT(625) AS 'KAREKÖK'

--FLOOR(): EN YAKIN KÜÇÜK SAYIYA YUVARLAR.
--CEILING(): EN YAKIN BÜYÜK SAYIYA YUVARLAR.
SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'

--TBLNOTLAR tablosundaki 1 numaralý öðrencinin Sinav1 notlarýnýn toplamý
SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1

SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

--1 NUMARALI ÖÐRENCÝNÝN ALMIÞ OLDUÐU DERSLER VE O DERSLERE AÝT 1.SINAV NOTLARI
SELECT DERSAD, SINAV1 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.DERSID WHERE OGRENCI=1

--AYÞE ÇINAR ADLI ÖÐRENCÝNÝN ALMIÞ OLDUÐU DERSLER VE O DERSLERE AÝT BÜTÜN SINAV NOTLARI
SELECT DERSAD, SINAV1, SINAV2, SINAV3 FROM TBLNOTLAR INNER JOIN TBLDERSLER 
ON TBLNOTLAR.DERS=TBLDERSLER.DERSID WHERE OGRENCI=(SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR')

