---------------------- BÖLÜM 19 - Trigger 2 ----------------------
use DbYeni
CREATE TABLE TBLMUSTERI
(
ID INT PRIMARY KEY IDENTITY(1,1),
AD VARCHAR(20),
SOYAD VARCHAR(20),
SEHIR VARCHAR(15),
BAKIYE DECIMAL(18,2)
)

CREATE TABLE TBLKATEGORI
(
KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
AD VARCHAR(20),
)

CREATE TABLE TBLURUN
(
URUNID INT PRIMARY KEY IDENTITY(1,1),
AD VARCHAR(20),
ALISFIYAT DECIMAL(18,2),
SATISFIYAT DECIMAL(18,2),
STOK SMALLINT,
DURUM BIT,
KATEGORI INT
)

CREATE TABLE TBLSATIS
(
SATISID INT PRIMARY KEY IDENTITY(1,1),
MUSTERI INT,
URUN INT,
TARIH DATE
)

UPDATE TBLSTOK SET TOPLAMURUN=(SELECT COUNT(*) FROM TBLURUN)

--Tetikleyiciyi oluþturmak için
CREATE TRIGGER ARTTIR
ON TBLURUN
AFTER INSERT
AS
UPDATE TBLSTOK SET TOPLAMURUN+=1


UPDATE TBLSTOK SET TOPLAMURUN=(SELECT SUM(STOK) FROM TBLURUN)

--Tetikleyiciyi silmek için
DROP TRIGGER ARTTIR

--Parametreli Trigger Kullanýmý
CREATE TRIGGER ARTTIR
ON TBLURUN
AFTER INSERT
AS
DECLARE @STOKSAYI INT
SELECT @STOKSAYI=STOK FROM inserted
UPDATE TBLSTOK SET TOPLAMURUN+=@STOKSAYI

CREATE TRIGGER AZALT
ON TBLURUN
AFTER DELETE
AS
DECLARE @STOKSAYI INT
SELECT @STOKSAYI=STOK FROM DELETED
UPDATE TBLSTOK SET TOPLAMURUN-=@STOKSAYI

INSERT INTO TBLURUN (AD,STOK) VALUES ('MIXER',80)

---------------------- BÖLÜM 20 - Transaction ----------------------
--ROLLBACK: Transaction içinde yapýlan iþlemi iptal eder. Veritabanýna yansýtmaz yani tabloya kaydetmez. Ama sorgu ekranýnda kaydý gösterir.
BEGIN TRANSACTION
INSERT INTO TBLKATEGORI (AD) VALUES ('TV')
INSERT INTO TBLKATEGORI (AD) VALUES ('HALI')
SELECT * FROM TBLKATEGORI
ROLLBACK

--COMMIT: Transaction içinde yapýlan bütün komutlar sorunsuz bir þekilde gerçekleþirse bunu Veritabanýna yansýtýr yani tabloya kaydeder.
BEGIN TRANSACTION
INSERT INTO TBLURUN(AD,STOK) VALUES ('ÜRÜN1',25)
INSERT INTO TBLURUN(AD,STOK) VALUES ('ÜRÜN2',40)
SELECT * FROM TBLURUN
COMMIT

--Eklenecek olan deðerlerden biri hatalý olduðu için hiçbir veriyi veritabanýna kaydetmedi
BEGIN TRANSACTION
INSERT INTO TBLURUN(AD,STOK) VALUES ('ÜRÜN3',10)
INSERT INTO TBLURUN(AD,STOK) VALUES ('ÜRÜN4','B')
SELECT * FROM TBLURUN
COMMIT

